Add files via upload

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -3,7 +3,7 @@
 #
 # Magisk Module Template Install Script
 # by topjohnwu
-# 
+#
 ##########################################################################################
 
 # Detect whether in boot mode
@@ -24,8 +24,12 @@ MAGISKBIN=/data/magisk
 # Default permissions
 umask 022
 
+# Initial cleanup
+rm -rf $TMPDIR 2>/dev/null
+mkdir -p $INSTALLER
+
 ##########################################################################################
-# Flashable update-binary preparation
+# Environment
 ##########################################################################################
 
 OUTFD=$2
@@ -34,7 +38,7 @@ ZIP=$3
 ui_print() {
   if $BOOTMODE; then
     echo "$1"
-  else 
+  else
     echo -n -e "ui_print $1\n" >> /proc/self/fd/$OUTFD
     echo -n -e "ui_print\n" >> /proc/self/fd/$OUTFD
   fi
@@ -43,7 +47,7 @@ ui_print() {
 require_new_magisk() {
   ui_print "***********************************"
   ui_print "! $MAGISKBIN isn't setup properly!"
-  ui_print "! Please install Magisk v13.1+!"
+  ui_print "! Please install Magisk v14.0+!"
   ui_print "***********************************"
   exit 1
 }
@@ -120,7 +124,7 @@ if [ -f /data/SYSINSTALL.CBL ]; then
   fi
   if [ -f /system/xbin/sqlite3 ]; then
    cp -af $INSTALLER/common/$SQLITE /system/xbin/sqlite3
-  set_perm  /system/xbin/sqlite3       0       0       0755 
+   set_perm  /system/xbin/sqlite3       0       0       0755 
   fi
   if [ ! -f /system/bin/sqlite3 ] && [ ! -f /system/xbin/sqlite3 ]; then
    cp -af $INSTALLER/common/$SQLITE /system/xbin/sqlite3
@@ -175,8 +179,7 @@ rm -af $MODPATH/system/xbin/haveged
 rm -af $MODPATH/system/etc/CrossBreeder/CHECK_PROCS
 rm -af $MODPATH/system/etc/CrossBreeder/CB_RunHaveged
 rm -af $MODPATH/system/etc/CrossBreeder/CB_RunDNSMasq
-rm -af $MODPATH/system/etc/CrossBreeder/dnrd.tcp.10053
-rm -af $MODPATH/system/etc/CrossBreeder/dnrd.udp.10053
+rm -af $MODPATH/system/etc/CrossBreeder/dnrd.10053
 rm -af $MODPATH/system/etc/CrossBreeder/zzCHECK_NET_DNS
 rm -af $MODPATH/system/etc/CrossBreeder/zzCrossBreeder
 rm -af $MODPATH/system/etc/CrossBreeder/punchmod
@@ -226,12 +229,11 @@ rm -af /system/xbin/haveged
 rm -af /system/etc/CrossBreeder/CHECK_PROCS
 rm -af /system/etc/CrossBreeder/CB_RunHaveged
 rm -af /system/etc/CrossBreeder/CB_RunDNSMasq
-rm -af /system/etc/CrossBreeder/dnrd.tcp.10053
-rm -af /system/etc/CrossBreeder/dnrd.udp.10053
+rm -af /system/etc/CrossBreeder/dnrd.10053
 rm -af /system/etc/CrossBreeder/zzCHECK_NET_DNS
 rm -af /system/etc/CrossBreeder/zzCrossBreeder
 rm -af /system/etc/CrossBreeder/punchmod
-rm -af /system/lib/modules/fransom.ko
+rm -af /system/lib/modules/frandom.ko
 rm -af /system/etc/CrossBreeder/ENTROPY_FEED_FREQUENCY_SECS
 rm -af /system/etc/CrossBreeder/IRQ_FLUSH_FREQUENCY_MINUTES
 cp -af $INSTALLER/common/zzCHECK_NET_DNS_X86 /system/etc/CrossBreeder/zzCHECK_NET_DNS
@@ -245,29 +247,45 @@ rm -af $INSTALLER/common/CrossBreeder/zzCrossBreeder/PUNCHMOD
 
 ###################################################
 
-# Mount /data to access MAGISKBIN
+ui_print "- Mounting /system, /vendor, /data, /cache"
+mount -o ro /system 2>/dev/null
+mount -o ro /vendor 2>/dev/null
 mount /data 2>/dev/null
+mount /cache 2>/dev/null
 
-# MAGISKBIN must exist, binaries and utility functions are placed there
-[ -d $MAGISKBIN -a -f $MAGISKBIN/magisk -a -f $MAGISKBIN/util_functions.sh ] || Install_to_system
-
+# Utility functions must exist
+[ -f $MAGISKBIN/util_functions.sh ] || Install_to_system
 # Load utility fuctions
 . $MAGISKBIN/util_functions.sh
-[ ! -z $SCRIPT_VERSION -a $SCRIPT_VERSION -ge 1310 ] || require_new_magisk
 get_outfd
 
-rm -rf $TMPDIR 2>/dev/null
-mkdir -p $INSTALLER
-unzip -o "$ZIP" config.sh -d $INSTALLER 2>/dev/null
+$BOOTMODE && ! is_mounted /magisk && abort "! Magisk is not activated!"
+[ ! -f /system/build.prop ] && abort "! /system could not be mounted!"
+
+# Detect version and architecture
+api_level_arch_detect
+
+# You can get the Android API version from $API, the CPU architecture from $ARCH
+# Useful if you are creating Android version / platform dependent mods
+
+# We need busybox/binaries to be setup
+$BOOTMODE && boot_actions || recovery_actions
 
 ##########################################################################################
-# Prepare
+# Preparation
 ##########################################################################################
+
+# Extract common files
+unzip -o "$ZIP" module.prop config.sh 'common/*' -d $INSTALLER 2>/dev/null
 
 [ ! -f $INSTALLER/config.sh ] && abort "! Unable to extract zip file!"
-
+# Load configurations
 . $INSTALLER/config.sh
 
+# Check the min magisk version
+MIN_VER=`grep_prop template $INSTALLER/module.prop`
+[ ! -z $MAGISK_VER_CODE -a $MAGISK_VER_CODE -ge $MIN_VER ] || require_new_magisk
+MODID=`grep_prop id $INSTALLER/module.prop`
 MODPATH=$MOUNTPATH/$MODID
 
 # Print mod name
@@ -278,38 +296,14 @@ ui_print "******************************"
 ui_print "Powered by Magisk (@topjohnwu)"
 ui_print "******************************"
 
-ui_print "- Mounting /system, /vendor, /data, /cache"
-mount -o ro /system 2>/dev/null
-mount -o ro /vendor 2>/dev/null
-mount /data 2>/dev/null
-mount /cache 2>/dev/null
-
-[ ! -f /data/magisk.img ] && abort "! Magisk is not installed"
-$BOOTMODE && ! is_mounted /magisk && abort "! Magisk is not activated!"
-[ ! -f /system/build.prop ] && abort "! /system could not be mounted!"
-
-# Detect version and architecture
-api_level_arch_detect
-
-# You can get the Android API version from $API, the CPU architecture from $ARCH
-# Useful if you are creating Android version / platform dependent mods
-
 ##########################################################################################
 # Install
 ##########################################################################################
 
-ui_print "- Extracting module files"
-unzip -o "$ZIP" -d $INSTALLER 2>/dev/null
-request_size_check $INSTALLER
-
-
-###################################################
-
-# We're going to use magisk binary now, require some recovery fixes
-$BOOTMODE || recovery_actions
+request_zip_size_check "$ZIP"
 
 if [ -f "$IMG" ]; then
-  ui_print "- $IMG detected!"
+  ui_print "- Found $IMG"
   image_size_check $IMG
   if [ "$reqSizeM" -gt "$curFreeM" ]; then
     newSizeM=$(((reqSizeM + curUsedM) / 32 * 32 + 64))
@@ -324,7 +318,7 @@ fi
 
 ui_print "- Mounting $IMG to $MOUNTPATH"
 MAGISKLOOP=`$MAGISKBIN/magisk --mountimg $IMG $MOUNTPATH`
-is_mounted $MOUNTPATH || abort"! $IMG mount failed..."
+is_mounted $MOUNTPATH || abort "! $IMG mount failed..."
 
 ###################################################
 
@@ -336,6 +330,7 @@ if [ -d $MODPATH ]; then
   rm -f $MOUNTPATH/.core/post-fs-data.d/CBL_initd.sh
   $MAGISKBIN/magisk --umountimg $MOUNTPATH $MAGISKLOOP
   rmdir $MOUNTPATH
+
   # Shrink the image if possible
   image_size_check $IMG
   newSizeM=$((curUsedM / 32 * 32 + 64))
@@ -343,7 +338,10 @@ if [ -d $MODPATH ]; then
     ui_print "- Shrinking $IMG to ${newSizeM}M"
     $MAGISKBIN/magisk --resizeimg $IMG $newSizeM
   fi
+
   $BOOTMODE || recovery_cleanup
+  rm -rf $TMPDIR
+
   ui_print "- Done"
   exit 0
 fi
@@ -352,13 +350,11 @@ fi
 
 # Create mod paths
 rm -rf $MODPATH 2>/dev/null
-rm -rf $MOUNTPATH/CBUL 2>/dev/null
-rm -rf $MOUNTPATH/CrossBreederLite 2>/dev/null
+rm -f $MOUNTPATH/.core/post-fs-data.d/CBL_initd.sh
 mkdir -p $MODPATH
 
-# Copy files
-ui_print "- Copying files"
-mv $INSTALLER/system $MODPATH/system
+ui_print "- Extracting module files"
+unzip -o "$ZIP" 'system/*' -d $MODPATH 2>/dev/null
 
 ###################################################
 
@@ -450,6 +446,7 @@ if [ $curSizeM -gt $newSizeM ]; then
 fi
 
 $BOOTMODE || recovery_cleanup
+rm -rf $TMPDIR
 
 ui_print "- Done"
 exit 0
